baseURL = "http://localhost:1313/"
languageCode = "en"
defaultContentLanguage = "en"
title = "overengineered"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
theme = "jane"
enableGitInfo = false # use git commit log to generate lastmod record
summaryLength = 30

# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

hasCJKLanguage = false    # has chinese/japanese/korean
paginate = 5
rssLimit = 30
disqusShortname = ""      # disqus_shortname
googleAnalytics = "UA-46396173-2"
copyright = ""            # default: author.name

[author]
  name = "Juozas Kontvainis"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
  post = "/:slug/"
  page = "/:slug/"

[params]
  #? debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda

  since = "2019"            # Site creation time
  homeFullContent = false
  rssFullContent = true


  # use public git repo url to link lastmod git commit, enableGitInfo should be true.
  #? gitRepo = ""

  # site info (optional)
  keywords = ["JavaScript", "jest", "testing"]
  description = "Juozas Kontvainis blog"

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?
  moreMeta = false

  # Syntax highlighting by highlight.js
  highlightInClient = false

  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe

  postMetaInFooter = false   # shows author, lastMod, markdown link, license
  contentCopyright = 'cprthldr'     # e.g. '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = []
  customJS = []

#  [params.utterances]       # https://utteranc.es/
#    owner = ""              # Your GitHub ID
#    repo = ""               # The repo to store comments

  [params.social]
    b-stack-overflow = "https://stackoverflow.com/users/64605/juozas-kontvainis"
    c-twitter = "https://twitter.com/@juoz4s"
    g-github = "https://github.com/overengineered"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.youtube]
    privacyEnhanced = true
